// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 304 01/25/2010)
// Created on Wed Apr 14 15:48:47 2010

//  Module Declaration
module UA
(
	// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
	p, clk, clkout, y, Z
	// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

	// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	input [4:1] p;
	input clk;
	output clkout;
	output [8:0] y;
	output Z;
	// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	integer pc=1;
	reg [8:0] y;
	wire clkout;
	reg Z=0;
	
assign clkout=!clk;
	
//always @(posedge clk)
//begin
//clkout=0;
//end

always @(posedge clk)
begin
case (pc)
	1:begin
	y=9'b000000011;
	pc= pc + 1;
	end
	2:begin
	if (p[1]==0) y=9'b000110000;
	else y=9'b000111100;
	pc = pc + 1;
	end
	3:begin
	y=9'b000000010;
	pc = pc + 1;
	end
	4:begin
	if (p[1]==0) y=9'b000010000;
	else y=9'b000011100;
	pc = pc + 1;
	end
	5:begin
	if (!p[2]&p[3]) begin
					y=9'b001000000;
					pc=8;
					end
	else if (!p[2]&!p[3]&!p[4])begin
							   Z=1;
							   y=9'b000000000;
							   pc = 8;
							   end
	else if (p[2]&!p[4])begin
						Z=1;
						y=9'b000000000;
						pc = 8;
						end
	else if (p[2]&p[4])begin
		 y=9'b010000000;
		 pc = pc + 1;
	end
	end
	6:begin
	y=9'b100011000;
	pc = pc + 1;
	end
	7:begin
	Z=1;
	y=9'b000000000;
	pc = pc + 1;
	end
	default y=9'b000000000;
endcase;
end


endmodule
